version: '3.5'
services:
  api:
    image: livematch/api
    hostname: livematch
    container_name: livematch_api
    depends_on:
      - rabbit
    ports:
      - "9090:9090"
    networks:
      livematchnet:
        aliases:
          - livematch

  postgres:
    image: postgres
    hostname: livematch_postgres
    container_name: livematch_postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TEST_SM
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      livematchnet:
        aliases:
          - livematch_db

  pgadmin:
    image: dpage/pgadmin4
    container_name: livematch_pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      livematchnet:
        aliases:
          - livematch_pgadmin

  rabbit:
    image: livematch/rabbit
    container_name: livematch_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      livematchnet:
        aliases:
          - livematch_rabbit

  livematch_consumers_newgoal:
    build:
      context: consumers/newGoal
    image: livematch_consumers_newgoal
    hostname: livematch_consumers_newgoal
    container_name: livematch_consumers_newgoal
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbit
    networks:
      livematchnet:
        aliases:
          - livematch_consumers_newgoal

  livematch_consumers_startmatch:
    build:
      context: consumers/startMatch
    image: livematch/consumers/startmatch
    hostname: livematch_consumers_startmatch
    container_name: livematch_consumers_startmatch
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbit
    networks:
      livematchnet:
        aliases:
          - livematch_consumers_startmatch

  livematch_consumers_endmatch:
    build:
      context: consumers/endMatch
    image: livematch/consumers/endmatch
    hostname: livematch_consumers_endmatch
    container_name: livematch_consumers_endmatch
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbit
    networks:
      livematchnet:
        aliases:
          - livematch_consumers_endmatch

  livematch_consumers_newoffside:
    build:
      context: consumers/newOffside
    image: livematch/consumers/newoffside
    hostname: livematch_consumers_newoffside
    container_name: livematch_consumers_newoffside
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbit
    networks:
      livematchnet:
        aliases:
          - livematch_consumers_newoffside

  livematch_consumers_newyellowcard:
    build:
      context: consumers/newYellowCard
    image: livematch/consumers/newyellowcard
    hostname: livematch_consumers_newyellowcard
    container_name: livematch_consumers_newyellowcard
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbit
    networks:
      livematchnet:
        aliases:
          - livematch_consumers_newyellowcard

  livematch_consumers_newredcard:
    build:
      context: consumers/newRedCard
    image: livematch/consumers/newredcard
    hostname: livematch_consumers_newredcard
    container_name: livematch_consumers_newredcard
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbit
    networks:
      livematchnet:
        aliases:
          - livematch_consumers_newredcard

  livematch_consumers_newsubstitution:
    build:
      context: consumers/newSubstitution
    image: livematch/consumers/newsubstitution
    hostname: livematch_consumers_newsubstitution
    container_name: livematch_consumers_newsubstitution
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbit
    networks:
      livematchnet:
        aliases:
          - livematch_consumers_newsubstitution

  livematch_consumers_newpenalty:
    build:
      context: consumers/newPenalty
    image: livematch/consumers/newpenalty
    hostname: livematch_consumers_newpenalty
    container_name: livematch_consumers_newpenalty
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbit
    networks:
      livematchnet:
        aliases:
          - livematch_consumers_newpenalty

volumes:
  postgres-data:

networks:
  livematchnet:
    external: true
    name: livematch_net