version: '3.5'
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: livematch_postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TEST_SM
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      livematchnet:
        aliases:
          - livematch_db

  pgadmin:
    image: dpage/pgadmin4
    container_name: livematch_pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      livematchnet:
        aliases:
          - livematch_pgadmin

  redis:
    image: redis
    container_name: livematch_redis
    networks:
      livematchnet:
        aliases:
          - livematch_redis

volumes:
  postgres-data:

networks:
  livematchnet:
    external: true
    name: livematch_net