version: '3.5'
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: livematch_newgoal_test_postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TEST_SM
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      livematch_newGoal_test_net:
        aliases:
          - livematch_db

  pgadmin:
    image: dpage/pgadmin4
    container_name: livematch_newgoal_test_pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      livematch_newGoal_test_net:
        aliases:
          - livematch_pgadmin

  rabbit:
    image: livematch_rabbit
    container_name: livematch_newgoal_test_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      livematch_newGoal_test_net:
        aliases:
          - livematch_rabbit

  livematch_consumers_newgoal:
    build:
      context: ../consumers/newGoal
    image: livematch_consumers_newgoal_test
    hostname: livematch_consumers_newgoal
    container_name: livematch_consumers_newgoal_test
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbit
    networks:
      livematch_newGoal_test_net:
        aliases:
          - livematch_consumers_newgoal

volumes:
  postgres-data:

networks:
  livematch_newGoal_test_net:
    external: true
    name: livematch_net